#### List
GET http://localhost:2020/api/users
Authorization: Bearer kangketik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9ucyI6eyJpZCI6MSwibGV2ZWwiOjEsIm5hbWEiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImlhdCI6MTYwNDQ3NTM4N30sImlhdCI6MTYwNDQ3NTY0MywiZXhwIjoxNjA0NDc5MjQzfQ.BF28Y2FjOKxvxYaO1RIqKoaOZtuyhX3SPaFZnf8xAs4

#### Detail
GET http://localhost:2020/api/users/9
Authorization: Bearer kangketik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9ucyI6eyJpZCI6MSwibGV2ZWwiOjEsIm5hbWEiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImlhdCI6MTYwNDQ3NTM4N30sImlhdCI6MTYwNDQ3NTY0MywiZXhwIjoxNjA0NDc5MjQzfQ.BF28Y2FjOKxvxYaO1RIqKoaOZtuyhX3SPaFZnf8xAs4

#### Save
POST http://localhost:2020/api/users/
Authorization: Bearer kangketik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9ucyI6eyJpZCI6MSwibGV2ZWwiOjEsIm5hbWEiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImlhdCI6MTYwNDQ3NTM4N30sImlhdCI6MTYwNDQ3NTY0MywiZXhwIjoxNjA0NDc5MjQzfQ.BF28Y2FjOKxvxYaO1RIqKoaOZtuyhX3SPaFZnf8xAs4

{
	"levels_id": 1,
	"users_code": "102136612493688109373",
	"users_name": "Akasaka Ryuunosuke",
	"users_login": "akasakaryu122",
	"users_pass": "older45.,"
}

#### Update
PUT http://localhost:2020/api/users/9
Authorization: Bearer kangketik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9ucyI6eyJpZCI6MSwibGV2ZWwiOjEsIm5hbWEiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImlhdCI6MTYwNDQ3NTM4N30sImlhdCI6MTYwNDQ3NTY0MywiZXhwIjoxNjA0NDc5MjQzfQ.BF28Y2FjOKxvxYaO1RIqKoaOZtuyhX3SPaFZnf8xAs4

{
	"levels_id": 1,
	"users_code": "102136612493688109373",
	"users_name": "Akasaka Ryuunosuke",
	"users_login": "asd",
	"users_pass": "older45.,"
}

#### Soft Delete
PATCH http://localhost:2020/api/users/9
Authorization: Bearer kangketik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9ucyI6eyJpZCI6MSwibGV2ZWwiOjEsIm5hbWEiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImlhdCI6MTYwNDQ3NTM4N30sImlhdCI6MTYwNDQ3NTY0MywiZXhwIjoxNjA0NDc5MjQzfQ.BF28Y2FjOKxvxYaO1RIqKoaOZtuyhX3SPaFZnf8xAs4

#### Hard Delete
DELETE http://localhost:2020/api/users/8
Authorization: Bearer kangketik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9ucyI6eyJpZCI6MSwibGV2ZWwiOjEsIm5hbWEiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImlhdCI6MTYwNDQ3NTM4N30sImlhdCI6MTYwNDQ3NTY0MywiZXhwIjoxNjA0NDc5MjQzfQ.BF28Y2FjOKxvxYaO1RIqKoaOZtuyhX3SPaFZnf8xAs4